/**
 * Shape of one row in `airports.json`, generated by scripts/build-airports.ts.
 *
 * Kept in its own module so the combobox can type the data without importing
 * the JSON itself — the point of loading that lazily is that it stays out of
 * the bundle until someone focuses the field.
 */
export type Airport = {
  /** Three-letter IATA code, e.g. "IST". Unique, and the sort key. */
  iata: string;
  /** Latin city name, e.g. "Istanbul". Always present. */
  city: string;
  /** Macedonian city name, e.g. "Истанбул". Absent for roughly a quarter. */
  cityMk?: string;
  /** Tells sibling airports apart: "Sabiha" → "Istanbul (Sabiha)". */
  qualifier?: string;
  qualifierMk?: string;
  /** Country name in English, e.g. "Turkey". */
  country: string;
  countryMk?: string;
  /**
   * Full airport name, searched but never shown — and only present when it adds
   * something the city doesn't. "Istanbul Airport" is dropped; "Sabiha Gökçen
   * Havalimanı" is kept.
   */
  name?: string;
  /** Alternate names and old codes from upstream — "Londres", "NYC". */
  keywords?: string;
  /** A large airport rather than a medium one. Breaks ranking ties. */
  big?: boolean;
  /**
   * The one people mean when they name the city. London has five airports and
   * "лондон" should lead with Heathrow, not whichever sorts first.
   */
  primary?: boolean;
};

/** How the row reads in the given locale, falling back to Latin. */
export function airportLabel(a: Airport, mk: boolean): string {
  const city = (mk && a.cityMk) || a.city || a.name || a.iata;
  const qualifier = mk ? a.qualifierMk ?? a.qualifier : a.qualifier;
  return qualifier ? `${city} (${qualifier})` : city;
}

export function airportCountry(a: Airport, mk: boolean): string {
  return (mk && a.countryMk) || a.country;
}

/**
 * Rank an airport against a query, or null when it doesn't match.
 * Lower is better.
 *
 * Matching is substring rather than prefix on purpose: the client's reference
 * returns Приштина and Бристол for "ist", because *Pr·ist·ina* and *Br·ist·ol*
 * both contain it. Ranking is what stops that behaviour being useless — plain
 * substring order would put Bristol above Istanbul for the same query.
 */
export function rankAirport(a: Airport, q: string): number | null {
  const needle = q.trim().toLowerCase();
  if (!needle) return null;

  const iata = a.iata.toLowerCase();
  // Defensive: the generator guarantees a city, but this data is regenerated
  // from two external sources and a crash here would take the whole form down.
  const city = (a.city ?? "").toLowerCase();
  const cityMk = a.cityMk?.toLowerCase() ?? "";

  if (iata === needle) return 0;                                   // exact code
  if (cityMk.startsWith(needle)) return 1;                          // МК city start
  if (city.startsWith(needle)) return 2;                            // Latin city start
  if (iata.startsWith(needle)) return 3;
  if (cityMk.includes(needle) || city.includes(needle)) return 4;   // city anywhere

  // Alias matching in three grades, because "wien" hits Vienna (alias "Wien"),
  // Poznań ("Henryk Wieniawski") and Kotzebue ("Ralph Wien Memorial") alike.
  // Whole word beats start-of-word beats buried-anywhere — which is what puts
  // Vienna on top, where a flat substring test left it behind Poznań.
  const aliases = `${a.keywords ?? ""} ${a.name ?? ""}`.toLowerCase().split(/[\s,\u2013\u2014/()-]+/);
  if (aliases.some((w) => w === needle)) return 5;                  // whole alias
  if (aliases.some((w) => w.startsWith(needle))) return 6;          // alias prefix

  const rest = `${a.name ?? ""} ${a.country} ${a.countryMk ?? ""} ${a.keywords ?? ""}`.toLowerCase();
  if (rest.includes(needle)) return 7;                              // anywhere at all
  return null;
}

/**
 * The airports matching a query, best first.
 *
 * Text relevance decides first; size breaks the tie. Without the size rule
 * "париз" leads with Paris-Vatry and "лондон" with London City, because every
 * candidate scores identically on the city name and the sort then falls back to
 * something arbitrary. The traveller means the big one.
 */
export function searchAirports(list: Airport[], query: string, limit = 8): Airport[] {
  if (query.trim().length < 2) return [];
  return list
    .map((a) => ({ a, r: rankAirport(a, query) }))
    .filter((x): x is { a: Airport; r: number } => x.r !== null)
    .sort(
      (x, y) =>
        x.r - y.r ||
        Number(Boolean(y.a.primary)) - Number(Boolean(x.a.primary)) ||
        Number(Boolean(y.a.big)) - Number(Boolean(x.a.big)) ||
        (x.a.city ?? "").localeCompare(y.a.city ?? "") ||
        x.a.iata.localeCompare(y.a.iata),
    )
    .slice(0, limit)
    .map((x) => x.a);
}
